// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// readCount
long readCount(Rcpp::String acc);
RcppExport SEXP SRA2R_readCount(SEXP accSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::String >::type acc(accSEXP);
    __result = Rcpp::wrap(readCount(acc));
    return __result;
END_RCPP
}
// reads
List reads(Rcpp::String acc, int n);
RcppExport SEXP SRA2R_reads(SEXP accSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::String >::type acc(accSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(reads(acc, n));
    return __result;
END_RCPP
}
